export const SETTINGS_LOADED = 'SETTINGS_LOADED';
export const DATASTORE_LOADED = 'DATASTORE_LOADED';
export const TRANSACTIONS_LOADED = 'TRANSACTIONS_LOADED';
export const TRANSACTIONS_IMPORTED = 'TRANSACTIONS_IMPORTED';
